### ISSUE TITLE
Terminating event loop not possible?

### ISSUE THREAD

**Issue by osa1** [tailhook/rotor-stream#10]
It seems like even when all state machines return `Intent::done()` main loop does not return. As an example, I have a code like this:

```rust
loop_inst.add_machine_with(|scope| {
    Stream::<...>::new(sock, (), scope)
}).unwrap();
let ret = loop_inst.run();
println!("ret: {:?}", ret);
```

In my protocol implementation, I just return `Intent::done()` in every handler except `create()`, but the loop still never terminates. It seems like `fetch` example program in this repo also has the same problem, it never terminates.

I'm wondering whether this is by design or a bug. If this is by design, then I'm wondering

- How to re-initialize the `Transport` after a `EndOfStream` event?
- How to actually stop.

Thanks.

**Comment by tailhook** [comment]
`Intent::done()` terminates connection not the main loop. In git master version of rotor it will exit when there are no state machines running at the moment any more.

**Comment by tailhook** [comment]
You can also use `scope.shutdown_loop()` [like this](https://github.com/tailhook/rotor/blob/master/examples/telnet.rs#L82)
