### ISSUE TITLE
Sendfile support

### ISSUE THREAD

**Issue by kosta** [tailhook/rotor-stream#2]
Hi!

What's the best way to implement sendfile support? Does it belong to rotor-stream?

"Basic" functionality is wrapping libc::sendfile. But how to use it in rotor (-stream/-http)?

All the rotor-http stuff is based on the `Buf` abstraction - you can't use that with sendfile. 

To send a meaningful HTTP response, we first need to send HTTP Status, then some headers, then call sendfile. In the case of chunked responses, we might also need send some other arbitrary data afterwards. So we need an abstraction over `Buf` and `sendfile()` data.

Proposal: "Write" buffers (e.g. `Response` in the server) use `OutputBuf`, which is a `Vec<enum of Buf and Sendfile>`. If you write data to an `OutputBuf`:
- If last elem in `Vec` is `Buf`: just write to buf
- Else: Append a `Buf` and write to that.
  Similarly, if you call `sendfile()` on an `OutputBuf`, it always appends another `Sendfile` object.

Just a rough proposal from skimming through rotor-http and rotor-stream. In the blog posts, you mentioned you weren't sure yet how to enable sendfile. I personally don't like having the `Vec<Buf>` thing, but I see no alternative to allow interleaving sendfile & arbitrary sending of data. 

(Maybe as an optimization, we could have an enum that's only `Buf` or only `Sendfile` or `Vec<OutputBuf>` so we don't have the double indirection of `Vec<Buf>` where `Buf` is `Vec<u8>` when we don't need it. But let's decide on the simple approach first)

What do you think? Does this make any sense?

Cheers,
Kosta

**Comment by tailhook** [comment]
I'm a little bit in a hurry now, I'll make more thoughtful response later.

But as an alternative rotor-stream exposes socket directly in the transport interface. So probably we can use sendfile right on the socket, without any changes of the buffer. If there is something in the buffer you just wait for Flush event. This is fine in linux, as you don't have a way to combine sendfile with data from memory anyway.

But I'm not sure how well does it play with rotor-http. Probably it will make the latter much less safe to use.

**Comment by kosta** [comment]
Yeah, basically what I describe can be rephrased to "queue up `Buf`s and `Sendfile` and write the next one on Flush". I'll try to prototype something.

**Comment by tailhook** [comment]
I'm not sure I was clear enough. I mean in rotor-stream we can do this without a `Vec<Buf>` using purely state machine approach. Here is an altered [example from rotor-stream](https://github.com/tailhook/rotor-stream/blob/1efbcacfc674578b8baa657a53e91898cb16a5b0/examples/fetch.rs): https://gist.github.com/tailhook/7f9df0d53818549d40d7902779758771 (It's untested because I don't know is there any interface for sendfile), but I think the idea is pretty clear.

I think in rotor-http there is no flow control at the moment. I mean there is no way to wait for your data to be sent, the response can only be driven by the timeouts or external wakeups. This should be fixed, for example, by adding  `continue_response` method to `rotor_http::server::Server` which is called in `bytes_flushed`.

When the flow control problem is fixed, we just need a wrapper around `Transport::sendfile` to `rotor_http::server::Response` which ensures that `Content-Length` matches the length of file or some similar thing. (We should also support range requests)

**Comment by tailhook** [comment]
Hm, another alternative, is just to add another option to an `Expectation::ExpectFileSent { file: File, offset: u64, bytes: u64 }`. Unfortunately, this either means a `File` is a single type that you can send from, or there is a `Box<AsRawFd>` which is excessive memory allocation. It's also not clear how to pass ownership of the file back to the application (so file descriptor can be cached) if needed. Similarly this means you can't use single file descriptor to send a 1Gb file to two clients fetching the same file.

On the other hand this makes less iterations back and forth between rotor-stream and the application. I.e. application can say: send this 4Gb file, everything following is a job of the rotor-stream.

The question is: is there any other use cases for sendfile except HTTP static file serving? This may guide our decision a little bit better.

**Comment by kosta** [comment]
Haha, yeah I noticed after your reply that my "solution" was to introduce a very weird state machine into the `Buf` object. Maybe not the smartest idea :)

I'm currently trying to prototype using sendfile at all. I'll try to look into `Expectation`s, too.

I think serving static files is _the_ main use case for sendfile(). That's also the feature I'm interested in :) But I think a good test to re-use this for other purposes is e.g. sending some bytes, then a file, then some more bytes, then another file. If that is possible, I think the API should be pretty general-purpose. (We might also need that for Keep-Alive connections anyway?)

Currently, I'm struggling at knowing when I am done with writing to socket. That's outside the `Server` Trait, it seems. I hope that I'll be able get to that tomorrow.

**Comment by tailhook** [comment]
@kosta, do you already have a wrapper for a sendfile itself? (or is it already in mio/net2?)

**Comment by kosta** [comment]
Not really. I'm using libc directly at the moment. I looked in mio but wasn't aware of net2, so I didn't see anything. I might be able to take a look tonight, otherwise tomorrow.

**Comment by kosta** [comment]
Doesn't look it it. At least `git grep sendfile` doesn't find anything.

**Comment by tailhook** [comment]
I mean you should write that first. This will make it available on in `transport.socket()` directly.

Then it's probably good idea to prototype it on `http_server::server::Request` directly. When that interface is made more or less clean, it would be easier to find out whether it's worth to add it to rotor-stream.

**Comment by kosta** [comment]
Do you mean `rotor_http::server::Response`?

Ok, I'll try to look into adding sendfile to net2. The linux API is pretty straightforward, but the MacOS sendfile() API wants a non-null pointer to a size_t that it will write the number of bytes written to. So using sendfile() requires an allocation that can only be free'd after sendfile() is done. Not sure how to abstract that in a safe way in net2. On the other hand, maybe focus on linux and worry about Mac later :)

**Comment by tailhook** [comment]
> MacOS sendfile() API wants a non-null pointer to a size_t that it will write the number of bytes written to

It's fine to put it on stack. sendfile is already done when it exited from the function call.

> Do you mean rotor_http::server::Response?

Sure, I mean the response :)

**Comment by kosta** [comment]
Ah thank you, that makes much more sense and is much easier to use :)

**Comment by KostaCitrix** [comment]
Hi! 

Sorry for being unresponsive for so long.

If I have a server that uses rotor-stream and writes to that, what state is the stream wrapper in when the writing is done? I.e. Can the server request handler be called back when writing is done? 

I think that is crucial to have anyway to be able to 

write foo to Response
do something else
write bar to Response

If that is possible, we can leverage the same thing to be called back after sendfile is done. Or if you want to write something and then call sendfile, then call sendfile again and then write something else can do that as well.

Does that make any sense? :)

Cheers,
Kosta

**Comment by kosta** [comment]
Note: I originally posted this with the wrong account. Sorry for the confusion :)

Hi!

Sorry for being unresponsive for so long.

If I have a server that uses rotor-stream and writes to that, what state is the stream wrapper in when the writing is done? I.e. Can the server request handler be called back when writing is done?

I think that is crucial to have anyway to be able to

write foo to Response
do something else
write bar to Response

If that is possible, we can leverage the same thing to be called back after sendfile is done. E.g. you write something and then call sendfile, then call sendfile again and then write something else.

Does that make any sense? :)

Cheers,
Kosta

**Comment by kosta** [comment]
Closing, I think what I'm asking for is actually a `Future`... :)
