### ISSUE TITLE
Document `end` parameter of `Protocol::bytes_read`

### ISSUE THREAD

**Issue by osa1** [tailhook/rotor-stream#8]
It's not clear how that argument is supposed to be used. In my program I'm repeatedly getting `bytes_read` calls with `0` as `end`, even though the server is not sending anything. The problem is probably with this code:

```rust
transport.input().consume(end);
```

but it's hard to tell without knowing what `end` is.

**Comment by tailhook** [comment]
This is a number of bytes to be consumed (i.e the number of bytes that has been parsed and are not needed any more). [Documented here](http://tailhook.github.io/netbuf/netbuf/struct.Buf.html#method.consume). `end` variable presumably means the end of the current packet, but I'm not sure what the context of the code is.

Consuming zero bytes is noop.
